#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("RunnerTracker.Resource", IsApplication=true)]

namespace RunnerTracker
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::ModernHttpClient.Resource.String.library_name = global::RunnerTracker.Resource.String.library_name;
			global::PCLCrypto.Resource.String.ApplicationName = global::RunnerTracker.Resource.String.ApplicationName;
			global::PCLCrypto.Resource.String.Hello = global::RunnerTracker.Resource.String.Hello;
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int SlideRight = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int SlideUp = 2130968577;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010010
			public const int ambientEnabled = 2130771984;
			
			// aapt resource value: 0x7f010014
			public const int buttonSize = 2130771988;
			
			// aapt resource value: 0x7f010001
			public const int cameraBearing = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int cameraTargetLat = 2130771970;
			
			// aapt resource value: 0x7f010003
			public const int cameraTargetLng = 2130771971;
			
			// aapt resource value: 0x7f010004
			public const int cameraTilt = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int cameraZoom = 2130771973;
			
			// aapt resource value: 0x7f010013
			public const int circleCrop = 2130771987;
			
			// aapt resource value: 0x7f010015
			public const int colorScheme = 2130771989;
			
			// aapt resource value: 0x7f010012
			public const int imageAspectRatio = 2130771986;
			
			// aapt resource value: 0x7f010011
			public const int imageAspectRatioAdjust = 2130771985;
			
			// aapt resource value: 0x7f010006
			public const int liteMode = 2130771974;
			
			// aapt resource value: 0x7f010000
			public const int mapType = 2130771968;
			
			// aapt resource value: 0x7f010017
			public const int minTextSize = 2130771991;
			
			// aapt resource value: 0x7f010018
			public const int precision = 2130771992;
			
			// aapt resource value: 0x7f010016
			public const int scopeUris = 2130771990;
			
			// aapt resource value: 0x7f010019
			public const int sizeToFit = 2130771993;
			
			// aapt resource value: 0x7f010007
			public const int uiCompass = 2130771975;
			
			// aapt resource value: 0x7f01000f
			public const int uiMapToolbar = 2130771983;
			
			// aapt resource value: 0x7f010008
			public const int uiRotateGestures = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int uiScrollGestures = 2130771977;
			
			// aapt resource value: 0x7f01000a
			public const int uiTiltGestures = 2130771978;
			
			// aapt resource value: 0x7f01000b
			public const int uiZoomControls = 2130771979;
			
			// aapt resource value: 0x7f01000c
			public const int uiZoomGestures = 2130771980;
			
			// aapt resource value: 0x7f01000d
			public const int useViewLifecycle = 2130771981;
			
			// aapt resource value: 0x7f01000e
			public const int zOrderOnTop = 2130771982;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050043
			public const int AliceBlue = 2131034179;
			
			// aapt resource value: 0x7f050039
			public const int AntiqueWhite = 2131034169;
			
			// aapt resource value: 0x7f050093
			public const int Aqua = 2131034259;
			
			// aapt resource value: 0x7f050078
			public const int Aquamarine = 2131034232;
			
			// aapt resource value: 0x7f050041
			public const int Azure = 2131034177;
			
			// aapt resource value: 0x7f05003e
			public const int Beige = 2131034174;
			
			// aapt resource value: 0x7f050024
			public const int Bisque = 2131034148;
			
			// aapt resource value: 0x7f0500a2
			public const int Black = 2131034274;
			
			// aapt resource value: 0x7f050022
			public const int BlanchedAlmond = 2131034146;
			
			// aapt resource value: 0x7f05009e
			public const int Blue = 2131034270;
			
			// aapt resource value: 0x7f050071
			public const int BlueViolet = 2131034225;
			
			// aapt resource value: 0x7f050065
			public const int Brown = 2131034213;
			
			// aapt resource value: 0x7f05004b
			public const int BurlyWood = 2131034187;
			
			// aapt resource value: 0x7f050083
			public const int CadetBlue = 2131034243;
			
			// aapt resource value: 0x7f050079
			public const int Chartreuse = 2131034233;
			
			// aapt resource value: 0x7f050055
			public const int Chocolate = 2131034197;
			
			// aapt resource value: 0x7f05002e
			public const int Coral = 2131034158;
			
			// aapt resource value: 0x7f050082
			public const int CornflowerBlue = 2131034242;
			
			// aapt resource value: 0x7f05001e
			public const int Cornsilk = 2131034142;
			
			// aapt resource value: 0x7f05004e
			public const int Crimson = 2131034190;
			
			// aapt resource value: 0x7f050094
			public const int Cyan = 2131034260;
			
			// aapt resource value: 0x7f0500a0
			public const int DarkBlue = 2131034272;
			
			// aapt resource value: 0x7f05009a
			public const int DarkCyan = 2131034266;
			
			// aapt resource value: 0x7f05005d
			public const int DarkGoldenrod = 2131034205;
			
			// aapt resource value: 0x7f050064
			public const int DarkGray = 2131034212;
			
			// aapt resource value: 0x7f05009d
			public const int DarkGreen = 2131034269;
			
			// aapt resource value: 0x7f05005a
			public const int DarkKhaki = 2131034202;
			
			// aapt resource value: 0x7f05006f
			public const int DarkMagenta = 2131034223;
			
			// aapt resource value: 0x7f050084
			public const int DarkOliveGreen = 2131034244;
			
			// aapt resource value: 0x7f05002d
			public const int DarkOrange = 2131034157;
			
			// aapt resource value: 0x7f050068
			public const int DarkOrchid = 2131034216;
			
			// aapt resource value: 0x7f050070
			public const int DarkRed = 2131034224;
			
			// aapt resource value: 0x7f050048
			public const int DarkSalmon = 2131034184;
			
			// aapt resource value: 0x7f05006d
			public const int DarkSeaGreen = 2131034221;
			
			// aapt resource value: 0x7f050087
			public const int DarkSlateBlue = 2131034247;
			
			// aapt resource value: 0x7f05008d
			public const int DarkSlateGray = 2131034253;
			
			// aapt resource value: 0x7f050098
			public const int DarkTurquoise = 2131034264;
			
			// aapt resource value: 0x7f05006a
			public const int DarkViolet = 2131034218;
			
			// aapt resource value: 0x7f050032
			public const int DeepPink = 2131034162;
			
			// aapt resource value: 0x7f050099
			public const int DeepSkyBlue = 2131034265;
			
			// aapt resource value: 0x7f050080
			public const int DimGray = 2131034240;
			
			// aapt resource value: 0x7f050091
			public const int DodgerBlue = 2131034257;
			
			// aapt resource value: 0x7f05005e
			public const int FireBrick = 2131034206;
			
			// aapt resource value: 0x7f05001c
			public const int FloralWhite = 2131034140;
			
			// aapt resource value: 0x7f05008f
			public const int ForestGreen = 2131034255;
			
			// aapt resource value: 0x7f050033
			public const int Fuchsia = 2131034163;
			
			// aapt resource value: 0x7f05004d
			public const int Gainsboro = 2131034189;
			
			// aapt resource value: 0x7f05003b
			public const int GhostWhite = 2131034171;
			
			// aapt resource value: 0x7f050028
			public const int Gold = 2131034152;
			
			// aapt resource value: 0x7f050050
			public const int Goldenrod = 2131034192;
			
			// aapt resource value: 0x7f050074
			public const int Gray = 2131034228;
			
			// aapt resource value: 0x7f05009c
			public const int Green = 2131034268;
			
			// aapt resource value: 0x7f050062
			public const int GreenYellow = 2131034210;
			
			// aapt resource value: 0x7f050042
			public const int Honeydew = 2131034178;
			
			// aapt resource value: 0x7f05002f
			public const int HotPink = 2131034159;
			
			// aapt resource value: 0x7f050057
			public const int IndianRed = 2131034199;
			
			// aapt resource value: 0x7f050085
			public const int Indigo = 2131034245;
			
			// aapt resource value: 0x7f050018
			public const int Ivory = 2131034136;
			
			// aapt resource value: 0x7f050044
			public const int Khaki = 2131034180;
			
			// aapt resource value: 0x7f050049
			public const int Lavender = 2131034185;
			
			// aapt resource value: 0x7f050020
			public const int LavenderBlush = 2131034144;
			
			// aapt resource value: 0x7f05007a
			public const int LawnGreen = 2131034234;
			
			// aapt resource value: 0x7f05001d
			public const int LemonChiffon = 2131034141;
			
			// aapt resource value: 0x7f050063
			public const int LightBlue = 2131034211;
			
			// aapt resource value: 0x7f050045
			public const int LightCoral = 2131034181;
			
			// aapt resource value: 0x7f05004a
			public const int LightCyan = 2131034186;
			
			// aapt resource value: 0x7f050037
			public const int LightGoldenrodYellow = 2131034167;
			
			// aapt resource value: 0x7f05006c
			public const int LightGreen = 2131034220;
			
			// aapt resource value: 0x7f050053
			public const int LightGrey = 2131034195;
			
			// aapt resource value: 0x7f05002a
			public const int LightPink = 2131034154;
			
			// aapt resource value: 0x7f05002c
			public const int LightSalmon = 2131034156;
			
			// aapt resource value: 0x7f050090
			public const int LightSeaGreen = 2131034256;
			
			// aapt resource value: 0x7f050072
			public const int LightSkyBlue = 2131034226;
			
			// aapt resource value: 0x7f05007c
			public const int LightSlateGray = 2131034236;
			
			// aapt resource value: 0x7f050060
			public const int LightSteelBlue = 2131034208;
			
			// aapt resource value: 0x7f050019
			public const int LightYellow = 2131034137;
			
			// aapt resource value: 0x7f050096
			public const int Lime = 2131034262;
			
			// aapt resource value: 0x7f05008c
			public const int LimeGreen = 2131034252;
			
			// aapt resource value: 0x7f050038
			public const int Linen = 2131034168;
			
			// aapt resource value: 0x7f050034
			public const int Magenta = 2131034164;
			
			// aapt resource value: 0x7f050077
			public const int Maroon = 2131034231;
			
			// aapt resource value: 0x7f050081
			public const int MediumAquamarine = 2131034241;
			
			// aapt resource value: 0x7f05009f
			public const int MediumBlue = 2131034271;
			
			// aapt resource value: 0x7f05005c
			public const int MediumOrchid = 2131034204;
			
			// aapt resource value: 0x7f05006b
			public const int MediumPurple = 2131034219;
			
			// aapt resource value: 0x7f05008b
			public const int MediumSeaGreen = 2131034251;
			
			// aapt resource value: 0x7f05007b
			public const int MediumSlateBlue = 2131034235;
			
			// aapt resource value: 0x7f050097
			public const int MediumSpringGreen = 2131034263;
			
			// aapt resource value: 0x7f050086
			public const int MediumTurquoise = 2131034246;
			
			// aapt resource value: 0x7f050058
			public const int MediumVioletRed = 2131034200;
			
			// aapt resource value: 0x7f050092
			public const int MidnightBlue = 2131034258;
			
			// aapt resource value: 0x7f05003c
			public const int MintCream = 2131034172;
			
			// aapt resource value: 0x7f050023
			public const int MistyRose = 2131034147;
			
			// aapt resource value: 0x7f050025
			public const int Moccasin = 2131034149;
			
			// aapt resource value: 0x7f050026
			public const int NavajoWhite = 2131034150;
			
			// aapt resource value: 0x7f0500a1
			public const int Navy = 2131034273;
			
			// aapt resource value: 0x7f050036
			public const int OldLace = 2131034166;
			
			// aapt resource value: 0x7f050075
			public const int Olive = 2131034229;
			
			// aapt resource value: 0x7f05007e
			public const int OliveDrab = 2131034238;
			
			// aapt resource value: 0x7f05002b
			public const int Orange = 2131034155;
			
			// aapt resource value: 0x7f050031
			public const int OrangeRed = 2131034161;
			
			// aapt resource value: 0x7f050051
			public const int Orchid = 2131034193;
			
			// aapt resource value: 0x7f050046
			public const int PaleGoldenrod = 2131034182;
			
			// aapt resource value: 0x7f050069
			public const int PaleGreen = 2131034217;
			
			// aapt resource value: 0x7f050061
			public const int PaleTurquoise = 2131034209;
			
			// aapt resource value: 0x7f05004f
			public const int PaleVioletRed = 2131034191;
			
			// aapt resource value: 0x7f050021
			public const int PapayaWhip = 2131034145;
			
			// aapt resource value: 0x7f050027
			public const int PeachPuff = 2131034151;
			
			// aapt resource value: 0x7f050056
			public const int Peru = 2131034198;
			
			// aapt resource value: 0x7f050029
			public const int Pink = 2131034153;
			
			// aapt resource value: 0x7f05004c
			public const int Plum = 2131034188;
			
			// aapt resource value: 0x7f05005f
			public const int PowderBlue = 2131034207;
			
			// aapt resource value: 0x7f050076
			public const int Purple = 2131034230;
			
			// aapt resource value: 0x7f050035
			public const int Red = 2131034165;
			
			// aapt resource value: 0x7f05005b
			public const int RosyBrown = 2131034203;
			
			// aapt resource value: 0x7f050089
			public const int RoyalBlue = 2131034249;
			
			// aapt resource value: 0x7f05006e
			public const int SaddleBrown = 2131034222;
			
			// aapt resource value: 0x7f05003a
			public const int Salmon = 2131034170;
			
			// aapt resource value: 0x7f050040
			public const int SandyBrown = 2131034176;
			
			// aapt resource value: 0x7f05008e
			public const int SeaGreen = 2131034254;
			
			// aapt resource value: 0x7f05001f
			public const int Seashell = 2131034143;
			
			// aapt resource value: 0x7f050066
			public const int Sienna = 2131034214;
			
			// aapt resource value: 0x7f050059
			public const int Silver = 2131034201;
			
			// aapt resource value: 0x7f050073
			public const int SkyBlue = 2131034227;
			
			// aapt resource value: 0x7f05007f
			public const int SlateBlue = 2131034239;
			
			// aapt resource value: 0x7f05007d
			public const int SlateGray = 2131034237;
			
			// aapt resource value: 0x7f05001b
			public const int Snow = 2131034139;
			
			// aapt resource value: 0x7f050095
			public const int SpringGreen = 2131034261;
			
			// aapt resource value: 0x7f050088
			public const int SteelBlue = 2131034248;
			
			// aapt resource value: 0x7f050054
			public const int Tan = 2131034196;
			
			// aapt resource value: 0x7f05009b
			public const int Teal = 2131034267;
			
			// aapt resource value: 0x7f050052
			public const int Thistle = 2131034194;
			
			// aapt resource value: 0x7f050030
			public const int Tomato = 2131034160;
			
			// aapt resource value: 0x7f05008a
			public const int Turquoise = 2131034250;
			
			// aapt resource value: 0x7f050047
			public const int Violet = 2131034183;
			
			// aapt resource value: 0x7f05003f
			public const int Wheat = 2131034175;
			
			// aapt resource value: 0x7f050017
			public const int White = 2131034135;
			
			// aapt resource value: 0x7f05003d
			public const int WhiteSmoke = 2131034173;
			
			// aapt resource value: 0x7f05001a
			public const int Yellow = 2131034138;
			
			// aapt resource value: 0x7f050067
			public const int YellowGreen = 2131034215;
			
			// aapt resource value: 0x7f05000e
			public const int common_action_bar_splitter = 2131034126;
			
			// aapt resource value: 0x7f0500a3
			public const int common_google_signin_btn_text_dark = 2131034275;
			
			// aapt resource value: 0x7f05000f
			public const int common_google_signin_btn_text_dark_default = 2131034127;
			
			// aapt resource value: 0x7f050011
			public const int common_google_signin_btn_text_dark_disabled = 2131034129;
			
			// aapt resource value: 0x7f050012
			public const int common_google_signin_btn_text_dark_focused = 2131034130;
			
			// aapt resource value: 0x7f050010
			public const int common_google_signin_btn_text_dark_pressed = 2131034128;
			
			// aapt resource value: 0x7f0500a4
			public const int common_google_signin_btn_text_light = 2131034276;
			
			// aapt resource value: 0x7f050013
			public const int common_google_signin_btn_text_light_default = 2131034131;
			
			// aapt resource value: 0x7f050015
			public const int common_google_signin_btn_text_light_disabled = 2131034133;
			
			// aapt resource value: 0x7f050016
			public const int common_google_signin_btn_text_light_focused = 2131034134;
			
			// aapt resource value: 0x7f050014
			public const int common_google_signin_btn_text_light_pressed = 2131034132;
			
			// aapt resource value: 0x7f0500a5
			public const int common_plus_signin_btn_text_dark = 2131034277;
			
			// aapt resource value: 0x7f050006
			public const int common_plus_signin_btn_text_dark_default = 2131034118;
			
			// aapt resource value: 0x7f050008
			public const int common_plus_signin_btn_text_dark_disabled = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int common_plus_signin_btn_text_dark_focused = 2131034121;
			
			// aapt resource value: 0x7f050007
			public const int common_plus_signin_btn_text_dark_pressed = 2131034119;
			
			// aapt resource value: 0x7f0500a6
			public const int common_plus_signin_btn_text_light = 2131034278;
			
			// aapt resource value: 0x7f05000a
			public const int common_plus_signin_btn_text_light_default = 2131034122;
			
			// aapt resource value: 0x7f05000c
			public const int common_plus_signin_btn_text_light_disabled = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int common_plus_signin_btn_text_light_focused = 2131034125;
			
			// aapt resource value: 0x7f05000b
			public const int common_plus_signin_btn_text_light_pressed = 2131034123;
			
			// aapt resource value: 0x7f050002
			public const int place_autocomplete_prediction_primary_text = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int place_autocomplete_prediction_primary_text_highlight = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int place_autocomplete_prediction_secondary_text = 2131034116;
			
			// aapt resource value: 0x7f050001
			public const int place_autocomplete_search_hint = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int place_autocomplete_search_text = 2131034112;
			
			// aapt resource value: 0x7f050005
			public const int place_autocomplete_separator = 2131034117;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060000
			public const int place_autocomplete_button_padding = 2131099648;
			
			// aapt resource value: 0x7f060008
			public const int place_autocomplete_powered_by_google_height = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int place_autocomplete_powered_by_google_start = 2131099657;
			
			// aapt resource value: 0x7f060003
			public const int place_autocomplete_prediction_height = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int place_autocomplete_prediction_horizontal_margin = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int place_autocomplete_prediction_primary_text = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int place_autocomplete_prediction_secondary_text = 2131099654;
			
			// aapt resource value: 0x7f060002
			public const int place_autocomplete_progress_horizontal_margin = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int place_autocomplete_progress_size = 2131099649;
			
			// aapt resource value: 0x7f060007
			public const int place_autocomplete_separator_start = 2131099655;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ButtonSignUpStyle = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int common_full_open_on_phone = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int common_google_signin_btn_icon_dark = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int common_google_signin_btn_icon_dark_disabled = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int common_google_signin_btn_icon_dark_focused = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int common_google_signin_btn_icon_dark_normal = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int common_google_signin_btn_icon_dark_pressed = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int common_google_signin_btn_icon_light = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int common_google_signin_btn_icon_light_disabled = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int common_google_signin_btn_icon_light_focused = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int common_google_signin_btn_icon_light_normal = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int common_google_signin_btn_icon_light_pressed = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int common_google_signin_btn_text_dark = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int common_google_signin_btn_text_dark_disabled = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int common_google_signin_btn_text_dark_focused = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int common_google_signin_btn_text_dark_normal = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int common_google_signin_btn_text_dark_pressed = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int common_google_signin_btn_text_light = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int common_google_signin_btn_text_light_disabled = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int common_google_signin_btn_text_light_focused = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int common_google_signin_btn_text_light_normal = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int common_google_signin_btn_text_light_pressed = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int common_ic_googleplayservices = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int common_plus_signin_btn_icon_dark = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int common_plus_signin_btn_icon_dark_disabled = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int common_plus_signin_btn_icon_dark_focused = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int common_plus_signin_btn_icon_dark_normal = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int common_plus_signin_btn_icon_dark_pressed = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int common_plus_signin_btn_icon_light = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int common_plus_signin_btn_icon_light_disabled = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int common_plus_signin_btn_icon_light_focused = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int common_plus_signin_btn_icon_light_normal = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int common_plus_signin_btn_icon_light_pressed = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int common_plus_signin_btn_text_dark = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int common_plus_signin_btn_text_dark_disabled = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int common_plus_signin_btn_text_dark_focused = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int common_plus_signin_btn_text_dark_normal = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int common_plus_signin_btn_text_dark_pressed = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int common_plus_signin_btn_text_light = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int common_plus_signin_btn_text_light_disabled = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int common_plus_signin_btn_text_light_focused = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int common_plus_signin_btn_text_light_normal = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int common_plus_signin_btn_text_light_pressed = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int edit_text_style = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int Icon = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int places_ic_clear = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int places_ic_search = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int powered_by_google_dark = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int powered_by_google_light = 2130837552;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0a001b
			public const int DateTextView = 2131361819;
			
			// aapt resource value: 0x7f0a001c
			public const int DetailTextView = 2131361820;
			
			// aapt resource value: 0x7f0a001a
			public const int IdListView = 2131361818;
			
			// aapt resource value: 0x7f0a0011
			public const int MyButton = 2131361809;
			
			// aapt resource value: 0x7f0a001e
			public const int RunnerTrackDetailTextView = 2131361822;
			
			// aapt resource value: 0x7f0a0020
			public const int RunnerTrackMenuListView = 2131361824;
			
			// aapt resource value: 0x7f0a001d
			public const int RunnerTrackerId = 2131361821;
			
			// aapt resource value: 0x7f0a0005
			public const int adjust_height = 2131361797;
			
			// aapt resource value: 0x7f0a0006
			public const int adjust_width = 2131361798;
			
			// aapt resource value: 0x7f0a000a
			public const int auto = 2131361802;
			
			// aapt resource value: 0x7f0a0026
			public const int btnDeviceData = 2131361830;
			
			// aapt resource value: 0x7f0a0010
			public const int btnDialogEmail = 2131361808;
			
			// aapt resource value: 0x7f0a0022
			public const int btnGetCurrrentLocation = 2131361826;
			
			// aapt resource value: 0x7f0a0024
			public const int btnGetWeather = 2131361828;
			
			// aapt resource value: 0x7f0a000b
			public const int dark = 2131361803;
			
			// aapt resource value: 0x7f0a0021
			public const int externalMapButton = 2131361825;
			
			// aapt resource value: 0x7f0a0000
			public const int hybrid = 2131361792;
			
			// aapt resource value: 0x7f0a0007
			public const int icon_only = 2131361799;
			
			// aapt resource value: 0x7f0a000c
			public const int light = 2131361804;
			
			// aapt resource value: 0x7f0a001f
			public const int mapFrameLayout = 2131361823;
			
			// aapt resource value: 0x7f0a0001
			public const int none = 2131361793;
			
			// aapt resource value: 0x7f0a0002
			public const int normal = 2131361794;
			
			// aapt resource value: 0x7f0a0014
			public const int place_autocomplete_clear_button = 2131361812;
			
			// aapt resource value: 0x7f0a0016
			public const int place_autocomplete_powered_by_google = 2131361814;
			
			// aapt resource value: 0x7f0a0018
			public const int place_autocomplete_prediction_primary_text = 2131361816;
			
			// aapt resource value: 0x7f0a0019
			public const int place_autocomplete_prediction_secondary_text = 2131361817;
			
			// aapt resource value: 0x7f0a0017
			public const int place_autocomplete_progress = 2131361815;
			
			// aapt resource value: 0x7f0a0012
			public const int place_autocomplete_search_button = 2131361810;
			
			// aapt resource value: 0x7f0a0013
			public const int place_autocomplete_search_input = 2131361811;
			
			// aapt resource value: 0x7f0a0015
			public const int place_autocomplete_separator = 2131361813;
			
			// aapt resource value: 0x7f0a0027
			public const int receiveDataMsgBox = 2131361831;
			
			// aapt resource value: 0x7f0a0003
			public const int satellite = 2131361795;
			
			// aapt resource value: 0x7f0a0008
			public const int standard = 2131361800;
			
			// aapt resource value: 0x7f0a0004
			public const int terrain = 2131361796;
			
			// aapt resource value: 0x7f0a0023
			public const int txtCurrentLocation = 2131361827;
			
			// aapt resource value: 0x7f0a000e
			public const int txtEmail = 2131361806;
			
			// aapt resource value: 0x7f0a000d
			public const int txtFirstName = 2131361805;
			
			// aapt resource value: 0x7f0a000f
			public const int txtPassword = 2131361807;
			
			// aapt resource value: 0x7f0a0025
			public const int txtWeatherData = 2131361829;
			
			// aapt resource value: 0x7f0a0009
			public const int wide = 2131361801;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f080000
			public const int google_play_services_version = 2131230720;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int dialog_sign_up = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int place_autocomplete_fragment = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int place_autocomplete_item_powered_by_google = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int place_autocomplete_item_prediction = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int place_autocomplete_progress = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int RowStyleView = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int RunnerTrackerDetailView = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int RunnerTrackerMenuView = 2130903048;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070022
			public const int ApplicationName = 2131165218;
			
			// aapt resource value: 0x7f070021
			public const int Hello = 2131165217;
			
			// aapt resource value: 0x7f070003
			public const int auth_google_play_services_client_facebook_display_name = 2131165187;
			
			// aapt resource value: 0x7f070002
			public const int auth_google_play_services_client_google_display_name = 2131165186;
			
			// aapt resource value: 0x7f07001a
			public const int common_google_play_services_api_unavailable_text = 2131165210;
			
			// aapt resource value: 0x7f07000c
			public const int common_google_play_services_enable_button = 2131165196;
			
			// aapt resource value: 0x7f07000b
			public const int common_google_play_services_enable_text = 2131165195;
			
			// aapt resource value: 0x7f07000a
			public const int common_google_play_services_enable_title = 2131165194;
			
			// aapt resource value: 0x7f070009
			public const int common_google_play_services_install_button = 2131165193;
			
			// aapt resource value: 0x7f070007
			public const int common_google_play_services_install_text_phone = 2131165191;
			
			// aapt resource value: 0x7f070008
			public const int common_google_play_services_install_text_tablet = 2131165192;
			
			// aapt resource value: 0x7f070006
			public const int common_google_play_services_install_title = 2131165190;
			
			// aapt resource value: 0x7f070015
			public const int common_google_play_services_invalid_account_text = 2131165205;
			
			// aapt resource value: 0x7f070014
			public const int common_google_play_services_invalid_account_title = 2131165204;
			
			// aapt resource value: 0x7f070013
			public const int common_google_play_services_network_error_text = 2131165203;
			
			// aapt resource value: 0x7f070012
			public const int common_google_play_services_network_error_title = 2131165202;
			
			// aapt resource value: 0x7f070005
			public const int common_google_play_services_notification_ticker = 2131165189;
			
			// aapt resource value: 0x7f07001e
			public const int common_google_play_services_restricted_profile_text = 2131165214;
			
			// aapt resource value: 0x7f07001d
			public const int common_google_play_services_restricted_profile_title = 2131165213;
			
			// aapt resource value: 0x7f07001c
			public const int common_google_play_services_sign_in_failed_text = 2131165212;
			
			// aapt resource value: 0x7f07001b
			public const int common_google_play_services_sign_in_failed_title = 2131165211;
			
			// aapt resource value: 0x7f070004
			public const int common_google_play_services_unknown_issue = 2131165188;
			
			// aapt resource value: 0x7f070017
			public const int common_google_play_services_unsupported_text = 2131165207;
			
			// aapt resource value: 0x7f070016
			public const int common_google_play_services_unsupported_title = 2131165206;
			
			// aapt resource value: 0x7f070018
			public const int common_google_play_services_update_button = 2131165208;
			
			// aapt resource value: 0x7f07000e
			public const int common_google_play_services_update_text = 2131165198;
			
			// aapt resource value: 0x7f07000d
			public const int common_google_play_services_update_title = 2131165197;
			
			// aapt resource value: 0x7f070011
			public const int common_google_play_services_updating_text = 2131165201;
			
			// aapt resource value: 0x7f070010
			public const int common_google_play_services_updating_title = 2131165200;
			
			// aapt resource value: 0x7f07000f
			public const int common_google_play_services_wear_update_text = 2131165199;
			
			// aapt resource value: 0x7f070019
			public const int common_open_on_phone = 2131165209;
			
			// aapt resource value: 0x7f07001f
			public const int common_signin_button_text = 2131165215;
			
			// aapt resource value: 0x7f070020
			public const int common_signin_button_text_long = 2131165216;
			
			// aapt resource value: 0x7f070023
			public const int library_name = 2131165219;
			
			// aapt resource value: 0x7f070001
			public const int place_autocomplete_clear_button = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int place_autocomplete_search_hint = 2131165184;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f090000
			public const int dialogAnimation = 2131296256;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] AutofitTextView = new int[] {
					2130771991,
					2130771992,
					2130771993};
			
			// aapt resource value: 0
			public const int AutofitTextView_minTextSize = 0;
			
			// aapt resource value: 1
			public const int AutofitTextView_precision = 1;
			
			// aapt resource value: 2
			public const int AutofitTextView_sizeToFit = 2;
			
			public static int[] LoadingImageView = new int[] {
					2130771985,
					2130771986,
					2130771987};
			
			// aapt resource value: 2
			public const int LoadingImageView_circleCrop = 2;
			
			// aapt resource value: 1
			public const int LoadingImageView_imageAspectRatio = 1;
			
			// aapt resource value: 0
			public const int LoadingImageView_imageAspectRatioAdjust = 0;
			
			public static int[] MapAttrs = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984};
			
			// aapt resource value: 16
			public const int MapAttrs_ambientEnabled = 16;
			
			// aapt resource value: 1
			public const int MapAttrs_cameraBearing = 1;
			
			// aapt resource value: 2
			public const int MapAttrs_cameraTargetLat = 2;
			
			// aapt resource value: 3
			public const int MapAttrs_cameraTargetLng = 3;
			
			// aapt resource value: 4
			public const int MapAttrs_cameraTilt = 4;
			
			// aapt resource value: 5
			public const int MapAttrs_cameraZoom = 5;
			
			// aapt resource value: 6
			public const int MapAttrs_liteMode = 6;
			
			// aapt resource value: 0
			public const int MapAttrs_mapType = 0;
			
			// aapt resource value: 7
			public const int MapAttrs_uiCompass = 7;
			
			// aapt resource value: 15
			public const int MapAttrs_uiMapToolbar = 15;
			
			// aapt resource value: 8
			public const int MapAttrs_uiRotateGestures = 8;
			
			// aapt resource value: 9
			public const int MapAttrs_uiScrollGestures = 9;
			
			// aapt resource value: 10
			public const int MapAttrs_uiTiltGestures = 10;
			
			// aapt resource value: 11
			public const int MapAttrs_uiZoomControls = 11;
			
			// aapt resource value: 12
			public const int MapAttrs_uiZoomGestures = 12;
			
			// aapt resource value: 13
			public const int MapAttrs_useViewLifecycle = 13;
			
			// aapt resource value: 14
			public const int MapAttrs_zOrderOnTop = 14;
			
			public static int[] SignInButton = new int[] {
					2130771988,
					2130771989,
					2130771990};
			
			// aapt resource value: 0
			public const int SignInButton_buttonSize = 0;
			
			// aapt resource value: 1
			public const int SignInButton_colorScheme = 1;
			
			// aapt resource value: 2
			public const int SignInButton_scopeUris = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
